import PortfolioCarousel from "./PortfolioCarousel"

export default function PageContent() {
    return (
        <div className="page-content">
            <h2 id="title-portfolio">PORTFOLIO</h2>
            <PortfolioCarousel items={[0, 1, 2]} />
            <h2 id="title-1">TITRE 1</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo eget magna fermentum iaculis eu non diam. Bibendum ut tristique et egestas. Faucibus et molestie ac feugiat sed. Suspendisse ultrices gravida dictum fusce. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Ut faucibus pulvinar elementum integer. Ornare suspendisse sed nisi lacus sed. Ultrices in iaculis nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas. Vulputate odio ut enim blandit volutpat maecenas. Morbi tristique senectus et netus et. Magna sit amet purus gravida quis blandit turpis cursus in. Consectetur adipiscing elit pellentesque habitant morbi. Fermentum dui faucibus in ornare. Nisl pretium fusce id velit ut tortor pretium viverra. Augue interdum velit euismod in pellentesque massa placerat duis. Enim diam vulputate ut pharetra sit amet aliquam id diam.

Mauris a diam maecenas sed enim ut sem. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Justo laoreet sit amet cursus sit. Diam volutpat commodo sed egestas egestas fringilla phasellus. Quam nulla porttitor massa id neque aliquam vestibulum. Vitae justo eget magna fermentum. Faucibus in ornare quam viverra orci. Pretium lectus quam id leo in vitae turpis massa. Eu lobortis elementum nibh tellus molestie nunc. Et odio pellentesque diam volutpat commodo sed egestas. Condimentum id venenatis a condimentum vitae sapien. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Eget lorem dolor sed viverra ipsum nunc aliquet. Lacus sed turpis tincidunt id aliquet. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. A diam sollicitudin tempor id.

Ut tellus elementum sagittis vitae et leo duis ut diam. Egestas dui id ornare arcu. Mauris cursus mattis molestie a iaculis at erat. Ultrices mi tempus imperdiet nulla malesuada. Volutpat blandit aliquam etiam erat velit scelerisque. Nibh venenatis cras sed felis eget velit. At in tellus integer feugiat scelerisque varius morbi enim. Tristique nulla aliquet enim tortor. Feugiat nisl pretium fusce id velit ut tortor. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tellus integer feugiat scelerisque varius. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Eleifend donec pretium vulputate sapien. Amet facilisis magna etiam tempor orci eu lobortis elementum.

Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Urna duis convallis convallis tellus id. Morbi tempus iaculis urna id volutpat lacus laoreet non. Massa tincidunt dui ut ornare lectus. Egestas dui id ornare arcu odio. Eu sem integer vitae justo. Elementum integer enim neque volutpat. Arcu odio ut sem nulla pharetra diam sit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus mauris a diam maecenas sed enim. Mauris pharetra et ultrices neque. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Elit eget gravida cum sociis natoque penatibus et. Nisi lacus sed viverra tellus in hac. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Vitae nunc sed velit dignissim sodales ut eu sem. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Curabitur gravida arcu ac tortor dignissim convallis.

Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Orci ac auctor augue mauris. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Sollicitudin aliquam ultrices sagittis orci. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Nec tincidunt praesent semper feugiat nibh sed. Ultricies integer quis auctor elit sed vulputate mi sit. Egestas tellus rutrum tellus pellentesque. Nunc sed velit dignissim sodales ut eu sem. A erat nam at lectus urna duis convallis convallis. Magna etiam tempor orci eu lobortis elementum. Amet commodo nulla facilisi nullam vehicula ipsum a. Donec pretium vulputate sapien nec sagittis aliquam. Dolor morbi non arcu risus quis varius quam quisque id. Tempor id eu nisl nunc. Nulla facilisi morbi tempus iaculis urna id volutpat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Mattis nunc sed blandit libero. Integer quis auctor elit sed vulputate mi sit amet.</p>
            <h2 id="title-2">TITRE 2</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo eget magna fermentum iaculis eu non diam. Bibendum ut tristique et egestas. Faucibus et molestie ac feugiat sed. Suspendisse ultrices gravida dictum fusce. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Ut faucibus pulvinar elementum integer. Ornare suspendisse sed nisi lacus sed. Ultrices in iaculis nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas. Vulputate odio ut enim blandit volutpat maecenas. Morbi tristique senectus et netus et. Magna sit amet purus gravida quis blandit turpis cursus in. Consectetur adipiscing elit pellentesque habitant morbi. Fermentum dui faucibus in ornare. Nisl pretium fusce id velit ut tortor pretium viverra. Augue interdum velit euismod in pellentesque massa placerat duis. Enim diam vulputate ut pharetra sit amet aliquam id diam.

Mauris a diam maecenas sed enim ut sem. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Justo laoreet sit amet cursus sit. Diam volutpat commodo sed egestas egestas fringilla phasellus. Quam nulla porttitor massa id neque aliquam vestibulum. Vitae justo eget magna fermentum. Faucibus in ornare quam viverra orci. Pretium lectus quam id leo in vitae turpis massa. Eu lobortis elementum nibh tellus molestie nunc. Et odio pellentesque diam volutpat commodo sed egestas. Condimentum id venenatis a condimentum vitae sapien. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Eget lorem dolor sed viverra ipsum nunc aliquet. Lacus sed turpis tincidunt id aliquet. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. A diam sollicitudin tempor id.

Ut tellus elementum sagittis vitae et leo duis ut diam. Egestas dui id ornare arcu. Mauris cursus mattis molestie a iaculis at erat. Ultrices mi tempus imperdiet nulla malesuada. Volutpat blandit aliquam etiam erat velit scelerisque. Nibh venenatis cras sed felis eget velit. At in tellus integer feugiat scelerisque varius morbi enim. Tristique nulla aliquet enim tortor. Feugiat nisl pretium fusce id velit ut tortor. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tellus integer feugiat scelerisque varius. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Eleifend donec pretium vulputate sapien. Amet facilisis magna etiam tempor orci eu lobortis elementum.

Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Urna duis convallis convallis tellus id. Morbi tempus iaculis urna id volutpat lacus laoreet non. Massa tincidunt dui ut ornare lectus. Egestas dui id ornare arcu odio. Eu sem integer vitae justo. Elementum integer enim neque volutpat. Arcu odio ut sem nulla pharetra diam sit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus mauris a diam maecenas sed enim. Mauris pharetra et ultrices neque. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Elit eget gravida cum sociis natoque penatibus et. Nisi lacus sed viverra tellus in hac. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Vitae nunc sed velit dignissim sodales ut eu sem. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Curabitur gravida arcu ac tortor dignissim convallis.

Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Orci ac auctor augue mauris. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Sollicitudin aliquam ultrices sagittis orci. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Nec tincidunt praesent semper feugiat nibh sed. Ultricies integer quis auctor elit sed vulputate mi sit. Egestas tellus rutrum tellus pellentesque. Nunc sed velit dignissim sodales ut eu sem. A erat nam at lectus urna duis convallis convallis. Magna etiam tempor orci eu lobortis elementum. Amet commodo nulla facilisi nullam vehicula ipsum a. Donec pretium vulputate sapien nec sagittis aliquam. Dolor morbi non arcu risus quis varius quam quisque id. Tempor id eu nisl nunc. Nulla facilisi morbi tempus iaculis urna id volutpat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Mattis nunc sed blandit libero. Integer quis auctor elit sed vulputate mi sit amet.</p>
            <h2 id="title-3">TITRE 3</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo eget magna fermentum iaculis eu non diam. Bibendum ut tristique et egestas. Faucibus et molestie ac feugiat sed. Suspendisse ultrices gravida dictum fusce. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Ut faucibus pulvinar elementum integer. Ornare suspendisse sed nisi lacus sed. Ultrices in iaculis nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas. Vulputate odio ut enim blandit volutpat maecenas. Morbi tristique senectus et netus et. Magna sit amet purus gravida quis blandit turpis cursus in. Consectetur adipiscing elit pellentesque habitant morbi. Fermentum dui faucibus in ornare. Nisl pretium fusce id velit ut tortor pretium viverra. Augue interdum velit euismod in pellentesque massa placerat duis. Enim diam vulputate ut pharetra sit amet aliquam id diam.

Mauris a diam maecenas sed enim ut sem. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Justo laoreet sit amet cursus sit. Diam volutpat commodo sed egestas egestas fringilla phasellus. Quam nulla porttitor massa id neque aliquam vestibulum. Vitae justo eget magna fermentum. Faucibus in ornare quam viverra orci. Pretium lectus quam id leo in vitae turpis massa. Eu lobortis elementum nibh tellus molestie nunc. Et odio pellentesque diam volutpat commodo sed egestas. Condimentum id venenatis a condimentum vitae sapien. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Eget lorem dolor sed viverra ipsum nunc aliquet. Lacus sed turpis tincidunt id aliquet. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. A diam sollicitudin tempor id.

Ut tellus elementum sagittis vitae et leo duis ut diam. Egestas dui id ornare arcu. Mauris cursus mattis molestie a iaculis at erat. Ultrices mi tempus imperdiet nulla malesuada. Volutpat blandit aliquam etiam erat velit scelerisque. Nibh venenatis cras sed felis eget velit. At in tellus integer feugiat scelerisque varius morbi enim. Tristique nulla aliquet enim tortor. Feugiat nisl pretium fusce id velit ut tortor. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tellus integer feugiat scelerisque varius. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Eleifend donec pretium vulputate sapien. Amet facilisis magna etiam tempor orci eu lobortis elementum.

Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Urna duis convallis convallis tellus id. Morbi tempus iaculis urna id volutpat lacus laoreet non. Massa tincidunt dui ut ornare lectus. Egestas dui id ornare arcu odio. Eu sem integer vitae justo. Elementum integer enim neque volutpat. Arcu odio ut sem nulla pharetra diam sit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus mauris a diam maecenas sed enim. Mauris pharetra et ultrices neque. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Elit eget gravida cum sociis natoque penatibus et. Nisi lacus sed viverra tellus in hac. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Vitae nunc sed velit dignissim sodales ut eu sem. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Curabitur gravida arcu ac tortor dignissim convallis.

Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Orci ac auctor augue mauris. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Sollicitudin aliquam ultrices sagittis orci. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Nec tincidunt praesent semper feugiat nibh sed. Ultricies integer quis auctor elit sed vulputate mi sit. Egestas tellus rutrum tellus pellentesque. Nunc sed velit dignissim sodales ut eu sem. A erat nam at lectus urna duis convallis convallis. Magna etiam tempor orci eu lobortis elementum. Amet commodo nulla facilisi nullam vehicula ipsum a. Donec pretium vulputate sapien nec sagittis aliquam. Dolor morbi non arcu risus quis varius quam quisque id. Tempor id eu nisl nunc. Nulla facilisi morbi tempus iaculis urna id volutpat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Mattis nunc sed blandit libero. Integer quis auctor elit sed vulputate mi sit amet.</p>
            <h2 id="title-4">TITRE 4</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo eget magna fermentum iaculis eu non diam. Bibendum ut tristique et egestas. Faucibus et molestie ac feugiat sed. Suspendisse ultrices gravida dictum fusce. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Ut faucibus pulvinar elementum integer. Ornare suspendisse sed nisi lacus sed. Ultrices in iaculis nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas. Vulputate odio ut enim blandit volutpat maecenas. Morbi tristique senectus et netus et. Magna sit amet purus gravida quis blandit turpis cursus in. Consectetur adipiscing elit pellentesque habitant morbi. Fermentum dui faucibus in ornare. Nisl pretium fusce id velit ut tortor pretium viverra. Augue interdum velit euismod in pellentesque massa placerat duis. Enim diam vulputate ut pharetra sit amet aliquam id diam.

Mauris a diam maecenas sed enim ut sem. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Justo laoreet sit amet cursus sit. Diam volutpat commodo sed egestas egestas fringilla phasellus. Quam nulla porttitor massa id neque aliquam vestibulum. Vitae justo eget magna fermentum. Faucibus in ornare quam viverra orci. Pretium lectus quam id leo in vitae turpis massa. Eu lobortis elementum nibh tellus molestie nunc. Et odio pellentesque diam volutpat commodo sed egestas. Condimentum id venenatis a condimentum vitae sapien. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Eget lorem dolor sed viverra ipsum nunc aliquet. Lacus sed turpis tincidunt id aliquet. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. A diam sollicitudin tempor id.

Ut tellus elementum sagittis vitae et leo duis ut diam. Egestas dui id ornare arcu. Mauris cursus mattis molestie a iaculis at erat. Ultrices mi tempus imperdiet nulla malesuada. Volutpat blandit aliquam etiam erat velit scelerisque. Nibh venenatis cras sed felis eget velit. At in tellus integer feugiat scelerisque varius morbi enim. Tristique nulla aliquet enim tortor. Feugiat nisl pretium fusce id velit ut tortor. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tellus integer feugiat scelerisque varius. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Eleifend donec pretium vulputate sapien. Amet facilisis magna etiam tempor orci eu lobortis elementum.

Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Urna duis convallis convallis tellus id. Morbi tempus iaculis urna id volutpat lacus laoreet non. Massa tincidunt dui ut ornare lectus. Egestas dui id ornare arcu odio. Eu sem integer vitae justo. Elementum integer enim neque volutpat. Arcu odio ut sem nulla pharetra diam sit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus mauris a diam maecenas sed enim. Mauris pharetra et ultrices neque. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Elit eget gravida cum sociis natoque penatibus et. Nisi lacus sed viverra tellus in hac. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Vitae nunc sed velit dignissim sodales ut eu sem. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Curabitur gravida arcu ac tortor dignissim convallis.

Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Orci ac auctor augue mauris. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Sollicitudin aliquam ultrices sagittis orci. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Nec tincidunt praesent semper feugiat nibh sed. Ultricies integer quis auctor elit sed vulputate mi sit. Egestas tellus rutrum tellus pellentesque. Nunc sed velit dignissim sodales ut eu sem. A erat nam at lectus urna duis convallis convallis. Magna etiam tempor orci eu lobortis elementum. Amet commodo nulla facilisi nullam vehicula ipsum a. Donec pretium vulputate sapien nec sagittis aliquam. Dolor morbi non arcu risus quis varius quam quisque id. Tempor id eu nisl nunc. Nulla facilisi morbi tempus iaculis urna id volutpat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Mattis nunc sed blandit libero. Integer quis auctor elit sed vulputate mi sit amet.</p>
        </div>
    )
}